site_settings:
  tagging_enabled: true
  verbose_discourse_connect_logging: true
seed: 1
start_date: 2020-01-01
max_likes_count: 10
auth_plugin_enabled: true
allow_anonymous_to_impersonate: false
include_images_in_posts: false
new_user:
   username: new_user
   email: new_user@example.com
